import {
	FaCaretLeft,
	FaCopy,
	FaArrowAltCircleLeft,
	FaArrowAltCircleRight,
	FaEdit,
	FaPlus,
	FaHome,
	FaFacebook,
	FaGoogle,
	FaInstagram,
	FaPhone,
	FaTwitter,
	FaWhatsapp,
	FaYoutube,
	FaImage,
	FaChevronLeft,
	FaEnvelope,
	FaEnvelopeOpen,
	FaCaretDown,
	//FaSpinner,
	FaDesktop,
	FaMoon,
	FaSun,
	FaTablet,
	FaClipboard,
	FaShareAlt,
	FaLinkedin,
	FaEject,
	FaPencilAlt,
	FaPrint,
	FaTable,
	FaUser,
	FaBinoculars,
	FaPen,
	FaSave,
	FaAngleRight,
	FaArrowsAlt,
	FaCheckCircle,
	FaLongArrowAltLeft,
	//FaCheck,
	FaCaretRight,
	FaBuilding,
	FaRecycle,
	FaLongArrowAltRight,
	FaAngleLeft,
	FaRegClock,
} from "react-icons/fa";
import {
	MdGridView,
	MdGridGoldenratio,
	MdDelete,
	MdNotifications,
	MdVideoCameraFront,
	MdFitScreen,
	MdFullscreen,
	MdDeleteForever,
	MdRestore,
	MdManageSearch,
} from "react-icons/md";
import { RiArrowDropDownLine } from "react-icons/ri";
import { FcGoogle } from "react-icons/fc";
import { GrHide, GrView, GrCircleAlert } from "react-icons/gr";
import { IoGridOutline } from "react-icons/io5";
import { FaCheck, FaXmark } from "react-icons/fa6";
import { ImSpinner } from "react-icons/im";

const Icons = {
	CheckCircle: FaCheckCircle,
	Check: FaCheck,
	Xmark: FaXmark,
	ArrowsAlt: FaArrowsAlt,
	CaretLeft: FaCaretLeft,
	CaretRight: FaCaretRight,
	Copy: FaCopy,
	ArrowAltCircleLeft: FaArrowAltCircleLeft,
	ArrowAltCircleRight: FaArrowAltCircleRight,
	LongArrowAltLeft: FaLongArrowAltLeft,
	LongArrowAltRight: FaLongArrowAltRight,
	Plus: FaPlus,
	Edit: FaEdit,
	Home: FaHome,
	Facebook: FaFacebook,
	Google: FaGoogle,
	Image: FaImage,
	ChevronLeft: FaChevronLeft,
	Envelope: FaEnvelope,
	EnvelopeOpen: FaEnvelopeOpen,
	CaretDown: FaCaretDown,
	ArrowDropDownLine: RiArrowDropDownLine,
	GridView: MdGridView,
	Spinner: ImSpinner,
	GridGoldenratio: MdGridGoldenratio,
	Instagram: FaInstagram,
	Phone: FaPhone,
	Twitter: FaTwitter,
	Whatsapp: FaWhatsapp,
	Youtube: FaYoutube,
	Desktop: FaDesktop,
	Moon: FaMoon,
	Sun: FaSun,
	Tablet: FaTablet,
	ShareAlt: FaShareAlt,
	Clipboard: FaClipboard,
	Linkedin: FaLinkedin,
	Delete: MdDelete,
	Eject: FaEject,
	Notifications: MdNotifications,
	VideoCameraFront: MdVideoCameraFront,
	PencilAlt: FaPencilAlt,
	Print: FaPrint,
	Table: FaTable,
	User: FaUser,
	Binoculars: FaBinoculars,
	Pen: FaPen,
	Save: FaSave,
	AngleLeft: FaAngleLeft,
	AngleRight: FaAngleRight,
	FitScreen: MdFitScreen,
	Fullscreen: MdFullscreen,
	Building: FaBuilding,
	DeleteForever: MdDeleteForever,
	Restore: MdRestore,
	Recycle: FaRecycle,
	ManageSearch: MdManageSearch,
	PasswordView: GrView,
	PasswordHide: GrHide,
	Alert: GrCircleAlert,
	Clock: FaRegClock,
	GridOutline: IoGridOutline,
	Colored: {
		Google: FcGoogle,
	},
};

export { Icons };
